apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticate-service
  template:
    metadata:
      labels:
        app: authenticate-service
    spec:
      containers:
      - name: authenticate-service
        image: tranductung0701/authenticate-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: "development"
        - name: DATASOURCE_HOST
          value: "postgres-authenticate-service"
        - name: DATASOURCE_PORT
          value: "5432"
        - name: DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PASSWORD
        - name: DATASOURCE_DATABASE
          value: "authenticate_db"
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: authenticate-service
  namespace: microservices-app
spec:
  selector:
    app: authenticate-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP 