apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploads-pvc
  namespace: microservices-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: tranductung0701/image-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ALLOWED_ORIGINS
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: TODO_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TODO_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NOTIFICATION_SERVICE_URL
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_SECRET
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_PRIVATE_KEY
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_CLIENT_EMAIL
        - name: FIREBASE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_DATABASE_URL
        volumeMounts:
        - name: image-uploads
          mountPath: /app/uploads
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: image-uploads
        persistentVolumeClaim:
          claimName: image-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: microservices-app
spec:
  selector:
    app: image-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP 