apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: tranductung0701/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          value: "8083"
        - name: DATABASE_URL
          value: "postgresql://myuser:mypass@postgres-notification-service:5432/notification_db"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: TODO_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TODO_SERVICE_URL
        - name: IMAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: IMAGE_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices-app
spec:
  selector:
    app: notification-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP 