apiVersion: apps/v1
kind: Deployment
metadata:
  name: todotask-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todotask-service
  template:
    metadata:
      labels:
        app: todotask-service
    spec:
      containers:
      - name: todotask-service
        image: tranductung0701/todotask-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-todo-service:5432/todo_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SERVER_PORT
          value: "8082"
        - name: SPRING_CACHE_TYPE
          value: "NONE"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: todotask-service
  namespace: microservices-app
spec:
  selector:
    app: todotask-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP 