apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticate-service
  template:
    metadata:
      labels:
        app: authenticate-service
    spec:
      containers:
      - name: authenticate-service
        image: sleepynhi/authenticate-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: DATASOURCE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATASOURCE_HOST
        - name: DATASOURCE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATASOURCE_PORT
        - name: DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATASOURCE_USERNAME
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATASOURCE_PASSWORD
        - name: DATASOURCE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATASOURCE_DATABASE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20