apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: sleepynhi/image-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_SECRET
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_PRIVATE_KEY
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FIREBASE_CLIENT_EMAIL
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: cors-config
              key: ALLOWED_ORIGINS
        - name: CORS_METHODS
          valueFrom:
            configMapKeyRef:
              name: cors-config
              key: CORS_METHODS
        - name: CORS_HEADERS
          valueFrom:
            configMapKeyRef:
              name: cors-config
              key: CORS_HEADERS
        - name: CORS_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: cors-config
              key: CORS_CREDENTIALS
        volumeMounts:
        - name: image-uploads
          mountPath: /app/uploads
      volumes:
      - name: image-uploads
        persistentVolumeClaim:
          claimName: image-uploads-pvc