apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-todo
spec:
  serviceName: postgres-todo-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-todo
  template:
    metadata:
      labels:
        app: postgres-todo
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: todo_db
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        volumeMounts:
        - name: postgres-todo-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "myuser", "-d", "todo_db"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "myuser", "-d", "todo_db"]
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: postgres-todo-storage
        persistentVolumeClaim:
          claimName: postgres-todo-pvc